---
title: "couchsurf"
author: "Mikhailov"
date: "06 05 2017"
output: html_document
---

# библиотеки
```{r}
set.seed(9)
library(jsonlite)
library(dplyr)
library(tidyr)
library(ggplot2)
library(caret)
library(recommenderlab)
library(ggmap)
library(rgdal)
library(leaflet)
```

# проитали json и привели в божеский вид
```{r}
setwd("~/repositories/couchsurfing")
df <- fromJSON("infol1.json", flatten=TRUE)
df <- bind_rows(df, .id = 'user_id')
```

#оставили только айди друганов и их страны
```{r}
attach(df)
df = dplyr::select(df, user_id, id, about.countries.visited)
df = dplyr::filter(df, about.countries.visited != "list()" )
      
#about.countries.lived, referenceCount, status, gender, publicAge, publicName, publicAddress.description)

# разлистили (перевели из list в обычный формат)
df = unnest(df, about.countries.visited)
df = dplyr::select(df, user_id, name)
```

#дамифицировали
```{r}
data_without_id = dplyr::select(df, name)
id = dplyr::select(df, user_id)


dmy = dummyVars("~.", data = data_without_id)
data.main = data.frame(predict(dmy, newdata = data_without_id))
data.main = bind_cols(id, data.main)
data.main = data.main %>% group_by(user_id) %>% summarise_each(funs(sum))
data.main$id_friend = as.numeric(data.main$user_id)

names(data.main) = substring(names(data.main), 5)
names(data.main)[1] = "user_id"
```

# попытались перевести данные в формат binaryRatingMatrix

```{r}
data.main = dplyr::select(data.main, -user_id)
data.main = ifelse(data.main>=1,1,0)
data_matrix = as.matrix(data.main)
data_matrix = as(data_matrix, "binaryRatingMatrix")
```

# разделение на тестовую и обучающую выборки
```{r}
test_ind <- sample(1:nrow(data_matrix), size = nrow(data_matrix)*0.2)
recc_data_train <- data_matrix[-test_ind, ]
recc_data_test <- data_matrix[test_ind, ]
```

# попытка построить рекоммендательную систему
```{r}
recc_model <- Recommender(data = recc_data_train, method = "UBCF")
#recc_model

#model_details <- getModel(recc_model)
#model_details$description
#model_details$sim[1:5, 1:5]

recc_predicted <- predict(object = recc_model, newdata = recc_data_test, n = 6)
#recc_predicted

#str(recc_predicted)

recc_user_1 <- recc_predicted@items[[5]]
recc_user_1
country_user_1 <- recc_predicted@itemLabels[recc_user_1]
country_user_1
```

```{r}
map = readOGR(dsn = '.', 'TM_WORLD_BORDERS-0_3')

output = data.frame(NAME = country_user_1)
map_filtered = map[ which(map@data$NAME %in% output$NAME ), "NAME"]

mymap <- leaflet() %>% 

addProviderTiles("Esri.WorldGrayCanvas") %>% 
fitBounds(50, 120, 20, 10) %>%
addPolygons(data = map, 
fillColor = 'green', ## we want the polygon filled with 
## one of the palette-colors
## according to the value in student1$Anteil
fillOpacity = 0.6, ## how transparent do you want the polygon to be?
color = "darkgrey", ## color of borders between districts
weight = 1.5, ## width of borders
# popup = popup1, ## which popup?
group="<span style='color: #7f0000; font-size: 11pt'><strong>2000</strong></span>") %>%
addPolygons(data = map_filtered, 
fillColor = 'red', ## we want the polygon filled with 
## one of the palette-colors
## according to the value in student1$Anteil
fillOpacity = 0.6, ## how transparent do you want the polygon to be?
color = "black", ## color of borders between districts
weight = 1, ## width of borders
# popup = popup1, ## which popup?
group="<span style='color: #7f0000; font-size: 11pt'><strong>2000</strong></span>")

mymap
```

